// app.js
export const CHANGE_LANGUEGE = 'CHANGE_LANGUEGE';
export const ADD_ACTIVEPAGE = 'ADD_ACTIVEPAGE';
export const REMOVE_ACTIVEPAGE = 'REMOVE_ACTIVEPAGE';
export const DELETE_CURRENT_ACTIVEPAGE = 'DELETE_CURRENT_ACTIVEPAGE';
export const DELETE_OTHERS_ACTIVEPAGE = 'DELETE_OTHERS_ACTIVEPAGE';
export const NEW_THEME_APPLY = 'NEW_THEME_APPLY';

// 登录
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

// 获取个人资料
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

// 获取用户权限
export const GET_USER_PERMISSION = 'GET_USER_PERMISSION';
export const GET_USER_PERMISSION_SUCCESS = 'GET_USER_PERMISSION_SUCCESS';
export const GET_USER_PERMISSION_FAILURE = 'GET_USER_PERMISSION_FAILURE';

// 退出
export const USER_LOGOUT = 'USER_LOGOUT';
